#!/usr/bin/env bash
# Usage: ./gen_condor_compressionx.sh --traces <trace_dir> --executable <champsim_exec>
#                   --rundir <run_dir> --user <notify_user> [--warmup <warmup_instrs> --simulation <sim_instrs>]
#
#
# Specific variant of gen_condor_compressed_champsim.sh which also passes the "-compression_ratio" flag, using data from
# standard in in the format:
# <BENCHMARK_NAME1> <COMPRESSION_RATIO1>
# <BENCHMARK_NAME2> <COMPRESSION_RATIO2>
# ...

OPTIONS=$(getopt -o t:e:r:w:s:u: --long traces:,executable:,rundir:,warmup:,simulation:,user: -- "$@")

if [ $? != 0 ]; then echo "Failed to parse options..." >& 2; exit 1; fi
eval set -- "$OPTIONS"

EXECUTABLE=
RUN_DIR=
TRACE_DIR=
USER=$(whoami)
WARMUP=10000000
SIMULATION=250000000

while true; do
    case "$1" in
        --traces|-t) TRACE_DIR=$2; shift 2;;
        --rundir|-r) RUN_DIR=$2; shift 2;;
        --executable|-e) EXECUTABLE=$2; shift 2;;
        --warmup|-w) WARMUP=$2; shift 2;;
        --simulation|-s) SIMULATION=$2; shift 2;;
        --user|-u) USER=$2; shift 2;;
        --) shift; break;;
        *) break;;
    esac
done

if [ -z "${EXECUTABLE}" ]; then
    echo "Please provide an executable to run"
    exit 1
fi

if [ -z "${RUN_DIR}" ]; then
    echo "Please provide a directory to run in and dump outputs to"
    exit 1
fi

if [ -z "${TRACE_DIR}" ]; then
    echo "Please provide a directory containing data traces"
    exit 1
fi

echo \#\#\#\#\#\#\#
echo \# AUTOGENERATED CONDOR FILE FOR COMPRESSED CHAMPSIM
echo \#\#\#\#\#\#\#

echo
echo +Group = \"UNDER\"
echo +Project = \"ARCHITECTURE\"
echo +ProjectDescription = \"Theoretical Bounds on Cache Performance\"
echo universe = vanilla
echo coresize = 0
echo getenv = true
echo Rank = Memory
echo notification = Error
echo notify_user = ${USER}@cs.utexas.edu
echo initialdir = ${RUN_DIR}
echo executable = ${EXECUTABLE}
echo

OUTPUT_DIR="${RUN_DIR}"
mkdir -p "${OUTPUT_DIR}"
mkdir -p "${OUTPUT_DIR}/condor_metadata"

while read line; do
    LINE_ARRAY=($line)

    # The benchmark we're running, and it's compression ratio.
    BENCHMARK=${LINE_ARRAY[0]}
    COMP_RATIO=${LINE_ARRAY[1]}

    TRACE_FILE=${TRACE_DIR}/${BENCHMARK}.gz

    echo \# Benchmark ${BENCHMARK}
    echo output=${OUTPUT_DIR}/${BENCHMARK}.out
    echo error=${OUTPUT_DIR}/condor_metadata/${BENCHMARK}.err
    echo log=${OUTPUT_DIR}/condor_metadata/${BENCHMARK}.log
    echo arguments=-compression_ratio ${COMP_RATIO} -warmup_instructions ${WARMUP} -simulation_instructions ${SIMULATION} -traces ${TRACE_FILE}
    echo queue
    echo
done
