#!/usr/bin/env bash
# Usage: ./gen_condor_compressed_champsim.sh --dumps <dump_dir> --executable <champsim_exec>
#                   --rundir <run_dir> --user <notify_user> [--chunk <chunk-size> --model
#                   <homogenous|heterogenous|superblock>]

OPTIONS=$(getopt -o d:e:r:u:c:m: --long dumps:,executable:,rundir:,user:,chunk:,model: -- "$@")

if [ $? != 0 ]; then echo "Failed to parse options..." >& 2; exit 1; fi
eval set -- "$OPTIONS"

EXECUTABLE=
RUN_DIR=
DUMP_DIR=
USER=$(whoami)
CHUNK_SIZE=32
MODEL="homogenous"

while true; do
    case "$1" in
        --dumps|-d) DUMP_DIR=$2; shift 2;;
        --rundir|-r) RUN_DIR=$2; shift 2;;
        --executable|-e) EXECUTABLE=$2; shift 2;;
        --user|-u) USER=$2; shift 2;;
        --chunk|-c) CHUNK_SIZE=$2; shift 2;;
        --model|-m) MODEL=$2; shift 2;;
        --) shift; break;;
        *) break;;
    esac
done

if [ -z "${EXECUTABLE}" ]; then
    echo "Please provide an executable to run"
    exit 1
fi

if [ -z "${RUN_DIR}" ]; then
    echo "Please provide a directory to run in and dump outputs to"
    exit 1
fi

if [ -z "${DUMP_DIR}" ]; then
    echo "Please provide the directory where interval dumps are located"
    exit 1
fi

echo \#\#\#\#\#\#\#
echo \# AUTOGENERATED CONDOR FILE FOR COMPRESSED CHAMPSIM
echo \#\#\#\#\#\#\#

echo
echo +Group = \"UNDER\"
echo +Project = \"ARCHITECTURE\"
echo +ProjectDescription = \"Theoretical Bounds on Cache Performance\"
echo universe = vanilla
echo coresize = 0
echo getenv = true
echo Rank = Memory
echo notification = Error
echo notify_user = ${USER}@cs.utexas.edu
echo initialdir = ${RUN_DIR}
echo executable = ${EXECUTABLE}
echo

OUTPUT_DIR="${RUN_DIR}"

for TRACE_NAME in $(ls ${DUMP_DIR}); do
    CSV_FILES=( $(ls ${DUMP_DIR}/${TRACE_NAME}) )
    NUM_CHUNKS=$((${#CSV_FILES[@]} / CHUNK_SIZE))
    FILE_DIR="${OUTPUT_DIR}/${TRACE_NAME}"
    mkdir -p ${FILE_DIR}
    mkdir -p ${FILE_DIR}/condor_metadata

    for CHUNK_ID in $(seq ${NUM_CHUNKS}); do
        ARGUMENTS=""
        for ARG_FILE in ${CSV_FILES[@]:$(((CHUNK_ID - 1) * CHUNK_SIZE)):CHUNK_SIZE}; do
            ARGUMENTS="${ARGUMENTS} ${DUMP_DIR}/${TRACE_NAME}/${ARG_FILE}"
        done


        echo \# Benchmark ${TRACE_NAME}, Chunk ${CHUNK_ID}
        echo output=${FILE_DIR}/chunk${CHUNK_ID}.out
        echo error=${FILE_DIR}/condor_metadata/chunk${CHUNK_ID}.err
        echo log=${FILE_DIR}/condor_metadata/chunk${CHUNK_ID}.log
        echo arguments=--model ${MODEL} ${ARGUMENTS}
        echo queue
        echo
    done
done
